name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install package dependencies
        run: npm install

      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: npm run lint

      - name: Create test build
        run: npm run build
